apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'https://github.com/LexNinvor/k8s-agrocd.git'
    targetRevision: master
    path: infr/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true